version: '3'

services:
  robot:
    build: services/robot
    image: ${IMAGE_PREFIX}-robot
    depends_on:
    - parser
    - add
    - sub
    - div
    - mult
    - neg
    - pow
    - mod
    environment:
      MC_ADD: '{"host": "add", "port": "3000"}'
      MC_SUB: '{"host": "sub", "port": "8000"}'
      MC_DIV: '{"host": "div", "port": "5000"}'
      MC_MULT: '{"host": "mult", "port": "8080"}'
      MC_NEG: '{"host": "neg", "port": "80"}'
      MC_POW: '{"host": "pow", "port": "3000"}'
      MC_MOD: '{"host": "mod", "port": "8080"}'
      MC_PARSER: '{"host": "parser", "port": "8080"}'
